### ISSUE TITLE
Binary builds for Apple Silicon M1 aarch64-darwin-20

### ISSUE THREAD

**Issue by lloeki** [rubyjs/libv8#309]
I will work on this once I receive M1-based hardware.

Tied to https://github.com/sqreen/ruby-libv8-node/issues/14

**Comment by angellozano67** [comment]
@lloeki Any luck? 😄

**Comment by lloeki** [comment]
Very much so.

This libv8 is of course a pain because of all the usual reasons (depot-tools and custom clang) but sqreen/ruby-libv8-node 15.0 built right away, and mini_racer (slightly patched to use that instead of this libv8) passes tests with flying colours.

There is a slight hitch with arm64 vs arm64e that I have not resolved yet and makes me uncomfortable publishing binaries right now.

I toyed with adding the M1 machine as a self-hosted GH Actions runner over there but without a proper virtualisation solution this means the runner has access to some personal files as well as my LAN.

**Comment by santostiago** [comment]
Hi @lloeki. 
What's the proper way to install the gem libv8 on a M1 macbook pro?
I've been struggling to install it with no success so far.

Thank you 😊

**Comment by lloeki** [comment]
There are a couple of snags such as [this one](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/259) (fixed somewhere on upstream v8 and [node 15.3](https://github.com/nodejs/node/pull/35986)).

I'm doing a rebuild of libv8-node based on 15.5.1 (I know, 15.6.0 is just out), I'll publish that as a beta along with a branch on rubyjs/mini_racer to use that instead of libv8 for people to try.

**Comment by lloeki** [comment]
@angellozano67 @santostiago Here goes (no strings attached), see the PR desc for how to use it: https://github.com/rubyjs/mini_racer/pull/186

**Comment by tisba** [comment]
Is this a problem with Apple Silicon, or arm in general, @lloeki?

In Docker for Mac on Apple Silicon, I get this (indicating on a problem around fetching source?!):

```
Installing libv8 7.3.492.27.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/libv8-7.3.492.27.1/ext/libv8
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.7.0 -r ./siteconf20210403-9-8a84ia.rb extconf.rb
creating Makefile
Traceback (most recent call last):
  File "/usr/local/bundle/gems/libv8-7.3.492.27.1/vendor/depot_tools/fetch.py", line 23, in <module>
    import json
ImportError: No module named json
/usr/local/bundle/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:83:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /usr/local/bundle/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:81:in `chdir'
	from /usr/local/bundle/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:81:in `setup_build_deps!'
	from /usr/local/bundle/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:40:in `build_libv8!'
	from /usr/local/bundle/gems/libv8-7.3.492.27.1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/libv8-7.3.492.27.1 for inspection.
Results logged to /usr/local/bundle/extensions/aarch64-linux/2.7.0/libv8-7.3.492.27.1/gem_make.out

An error occurred while installing libv8 (7.3.492.27.1), and Bundler cannot continue.
Make sure that `gem install libv8 -v '7.3.492.27.1' --source 'https://rubygems.org/'` succeeds before bundling.
```

**Comment by lloeki** [comment]
@tisba That problem will be solved wit the move to libv8-node. You can try [this PR](https://github.com/rubyjs/mini_racer/pull/186).

**Comment by tisba** [comment]
> @tisba That problem will be solved wit the move to libv8-node. You can try [this PR](https://github.com/rubyjs/mini_racer/pull/186).

yeah, I probably posted that too quickly, it makes no sense what I wrote in this context. Sorry for the noise.

But thank you, I'm already watching https://github.com/rubyjs/mini_racer/pull/186 very closely! We have some issue which requires to pin mini_racer to an old version (see https://github.com/rubyjs/mini_racer/issues/170). I haven't had the time to fully test https://github.com/rubyjs/mini_racer/pull/186 if it really solves our issue with forking.
