### ISSUE TITLE
Installing 7.3.492.27.1 fails to install intermittently with "ImportError: No module named json" on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by tisba** [rubyjs/libv8#316]
For some weeks, we get intermittent errors when trying to deploy our application to a server running Ubuntu 20.04.2 LTS. The cause is that libv8 (7.3.492.27.1) could not be installed.

I'm aware that this is not the latest version, but we are stuck with `mini_racer` at `0.2.15` (and therefore this older libv8 version) for quite some time because of https://github.com/rubyjs/mini_racer/issues/170 😞 

Here is the output from the deployment (using capistrano) that shows the error message:

```
"/app/shared/bundle/ruby/3.0.0/gems/libv8-7.3.492.27.1/vendor/depot_tools/fetch.py",
line 23, in <module>
    import json
ImportError: No module named json
```

<details>
<summary>Here is the same error with more context…</summary>

```
/usr/local/bundle/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as user@example.com: bundle exit status: 5 (SSHKit::Runner::ExecuteError)
bundle stdout: Nothing written
bundle stderr: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/app/shared/bundle/ruby/3.0.0/gems/libv8-7.3.492.27.1/ext/libv8
/usr/local/rvm/rubies/ruby-3.0.1/bin/ruby -I
/usr/local/rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0 -r
./siteconf20210518-1436780-o4ukc7.rb extconf.rb
creating Makefile
Traceback (most recent call last):
File
"/app/shared/bundle/ruby/3.0.0/gems/libv8-7.3.492.27.1/vendor/depot_tools/fetch.py",
line 23, in <module>
    import json
ImportError: No module named json
/app/shared/bundle/ruby/3.0.0/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:83:in
`block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
from
/app/shared/bundle/ruby/3.0.0/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:81:in
`chdir'
from
/app/shared/bundle/ruby/3.0.0/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:81:in
`setup_build_deps!'
from
/app/shared/bundle/ruby/3.0.0/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:40:in
`build_libv8!'
from
/app/shared/bundle/ruby/3.0.0/gems/libv8-7.3.492.27.1/ext/libv8/location.rb:24:in
`install!'
  from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in
/app/shared/bundle/ruby/3.0.0/gems/libv8-7.3.492.27.1 for inspection.
Results logged to
/app/shared/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/libv8-7.3.492.27.1/gem_make.out

An error occurred while installing libv8 (7.3.492.27.1), and Bundler cannot
continue.
Make sure that `gem install libv8 -v '7.3.492.27.1' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mini_racer was resolved to 0.2.15, which depends on
    libv8
  from /usr/local/bundle/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/usr/local/bundle/gems/sshkit-1.21.2/lib/sshkit/command.rb:97:in `exit_status=': bundle exit status: 5 (SSHKit::Command::Failed)
bundle stdout: Nothing written
bundle stderr: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```
</details>

Is there anything we can do to mitigate this issue? What does this `fetch.py` do? I'm also confused how they can be an intermittent load error 😕

**Comment by tisba** [comment]
I guess, this is no longer relevant. I haven't seen the issue in a long time, AFAIK not even once with versions past mini_racer 0.2.15.
